[functions]
    directory = "/server/api"

[[redirects]]
  from = "/api/song/blob"
  to = "/.netlify/functions/song-blob"
  status = 200
  force = true    

[[redirects]]
  from = "/api/*" # simplify all calls to serverless functions
  to = "/.netlify/functions/:splat" # all function calls will go to this path
  status = 200 # ok code
  force = true # ensure to always redirect

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"

[build]
    edge_functions  = "server/edge"