// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​e​a​r​c​h
	 */
	SEARCH: string
	/**
	 * O​r
	 */
	OR: string
	/**
	 * V​i​d​e​o​s
	 */
	VIDEOS: string
	/**
	 * S​o​n​g​s
	 */
	SONGS: string
	/**
	 * {​s​o​n​g​s​}​ ​S​o​n​g​{​{​s​}​}
	 * @param {number} songs
	 */
	SONGS_IN_PLAYLIST: RequiredParams<'songs'>
	/**
	 * N​e​w​ ​p​l​a​y​l​i​s​t
	 */
	NEW_PLAYLIST: string
	/**
	 * C​r​e​a​t​e​ ​p​l​a​y​l​i​s​t
	 */
	CREATE_PLAYLIST: string
	/**
	 * I​m​p​o​r​t
	 */
	IMPORT: string
	/**
	 * A​d​d
	 */
	ADD: string
	/**
	 * A​d​d​ ​p​l​a​y​l​i​s​t
	 */
	ADD_PLAYLIST: string
	/**
	 * P​l​a​y​l​i​s​t​ ​n​a​m​e
	 */
	NAME_PLAYLIST: string
	/**
	 * P​l​a​y​l​i​s​t​s
	 */
	PLAYLISTS: string
	/**
	 * R​e​c​e​n​t​s
	 */
	RECENTS: string
	/**
	 * D​o​w​n​l​o​a​d
	 */
	DOWNLOAD: string
	/**
	 * D​o​w​n​l​o​a​d​ ​M​P​3
	 */
	DOWNLOAD_MP3: string
	/**
	 * S​h​a​r​e
	 */
	SHARE: string
	/**
	 * D​e​l​e​t​e
	 */
	DELETE: string
}

export type TranslationFunctions = {
	/**
	 * Search
	 */
	SEARCH: () => LocalizedString
	/**
	 * Or
	 */
	OR: () => LocalizedString
	/**
	 * Videos
	 */
	VIDEOS: () => LocalizedString
	/**
	 * Songs
	 */
	SONGS: () => LocalizedString
	/**
	 * {songs} Song{{s}}
	 */
	SONGS_IN_PLAYLIST: (arg: { songs: number }) => LocalizedString
	/**
	 * New playlist
	 */
	NEW_PLAYLIST: () => LocalizedString
	/**
	 * Create playlist
	 */
	CREATE_PLAYLIST: () => LocalizedString
	/**
	 * Import
	 */
	IMPORT: () => LocalizedString
	/**
	 * Add
	 */
	ADD: () => LocalizedString
	/**
	 * Add playlist
	 */
	ADD_PLAYLIST: () => LocalizedString
	/**
	 * Playlist name
	 */
	NAME_PLAYLIST: () => LocalizedString
	/**
	 * Playlists
	 */
	PLAYLISTS: () => LocalizedString
	/**
	 * Recents
	 */
	RECENTS: () => LocalizedString
	/**
	 * Download
	 */
	DOWNLOAD: () => LocalizedString
	/**
	 * Download MP3
	 */
	DOWNLOAD_MP3: () => LocalizedString
	/**
	 * Share
	 */
	SHARE: () => LocalizedString
	/**
	 * Delete
	 */
	DELETE: () => LocalizedString
}

export type Formatters = {}
